language: go
go:
- '1.14'
before_install:
- go get -v github.com/mattn/goveralls
script:
- make all
- "$HOME/gopath/bin/goveralls -coverprofile=cover.out -service=travis-ci"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gYVdkDRCClHgB3HSB7X8p43RCgMUT+H4VqklhkFXxvtI+XfY3fv3Dg8uodsMJFbn8EQ9R/bt2Z0Tv8wx3qmnP9+GuXblJOLXg31a5ORVCIackhOQmydW2ne81o7yg3z3KTfqoc2rkWK9Wn3nOFBdyNMdgk7qL6VHzQMuhF8rm5H+7PiyQkNqp6eYSj0n6VWL0TMg8mVfIzPbEr30taIcQVBEHWZqUBXhoV8o34y20+Su/odo4Egc+CBXzSPYpfjxVk5L2RJdY/aciyDGLf7ouOFRAld0OrdlFhFsb6Fj4O4LE9DLGp/pr628jAaDfOHMSEi0jVhNPC8M79zT6g59Pfk+hEtetZ08hm3IpdnNTKFSR/FajTSzmJoL6Ny5x990i0pAEYZ0F44JJ3zUgqJR9thZ99AM9dgiRB6tbx3p+WrklFswRnxZgxI3e1UBs61Od+nuOvQdH6mDL2PmNjxSvitPoRpxsAu5zAdJAJXL25slwlzBheY0207ELt5m5n4eEDtVvL9ehrqOKlu69Py0f4KcC7drcggr36hoXDvXgj5qcuEyPqVpSMpDQcpMmqHZrP/0WFGptqx7PquFDjexFL9qcEr7YtLIexk1JH7bjuHi1mQsEIeZhQfcUPwjEgH02LOh96KsoIQ9Wwv1zmL4fw0xoWhjJlq28Y4X2d2P6Uc=
  file: "$GOPATH/src/github.com/wrouesnel/p2cli/p2"
  on:
    tags: true
    repo: wrouesnel/p2cli
