language: go
go:
- '1.14'
before_install:
- go get -v github.com/mattn/goveralls
script:
- make all
- "$HOME/gopath/bin/goveralls -coverprofile=cover.out -service=travis-ci"
deploy:
  provider: releases
  api_key:
    secure: lsib5909z6vwGjgOuyTbA3XIItT99CXFJ5XtGJVddm1/ZgkGwqlJjIFtmLZ5Y0oud0ScqWAAOS/ucZGTa3Q10bR6Bpw+nmgh3gJb9nU3pXqvthnay7ffOBXzyCuuaTKdId3UbZFU93mOiBNtCnbV2m5UXyf/n6SZXRHBoVpnjJwF5VTCNJNXi3Vslt5t+EYgeKaS/BfQ2kMdN6MpafYcAInBDklZu7ZhfcbNBiGz311OoPTS/+HAc1oysgu321OswegLAADb40UXvH/kaBcpqTG2EvNWGPEqeECpmjJdI1/9UgVUyASkqKOmBVk2Lskmfh7LJYb7OaWZumEQ+kMx2mKfuRvI89336jz3L++MnWJaQoLRgkUYqhhdV7DwuL91B5sVyLfKyS1MNHSJuexLgXq2vXdwWW0SU0epKhq1TKhT0FT2cG8WCN3Mo3y2puF5MaeRnsr6W6i0vq+sm5JNqBLtArv32XQrbc7PjP3nwDeL8E9lTREnNRY6sVSmgsrO/K0fYp6lE5V5uWDziBWlRUU6jvrtuQ9c3opLsxB1zh098Qm1A1LuZO2+kbWILXuPfHai86OvsOAr37iOVz2n4mo/WV48UjXFpObPz2yWHHa24mxafi+TRatgXWiQzC+lnJCNVokeVuVAEUNEJKN+ZHdkw3Lg9x3kQfbtmvA5j5s=
  file: "$GOPATH/src/github.com/wrouesnel/p2cli/p2"
  on:
    repo: wrouesnel/p2cli
    tags: true
